// Command codemap writes the book's code reference (docs/content/reference/
// code-map.md): every package, file, type and function of the repository,
// with the first sentence of its doc comment. The book explains the design;
// this page is generated from the source so it never goes stale.
//
//	go run ./hack/codemap > docs/content/reference/code-map.md   (make docs-codemap)
package main

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type symbol struct {
	name, kind, summary string
	exported            bool
}

type file struct {
	path    string
	lines   int
	test    bool
	summary string
	symbols []symbol
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	pkgs := map[string][]file{}
	pkgDoc := map[string]string{}
	var tsFiles []file
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		name := d.Name()
		if d.IsDir() {
			if name == "node_modules" || name == ".git" || name == "dist" || name == "testdata" || name == "docs" {
				return filepath.SkipDir
			}
			return nil
		}
		rel, _ := filepath.Rel(root, p)
		switch {
		case strings.HasSuffix(name, ".go") && !strings.HasPrefix(name, "zz_generated"):
			f, doc, err := goFile(p, rel)
			if err != nil {
				return err
			}
			dir := filepath.Dir(rel)
			pkgs[dir] = append(pkgs[dir], f)
			if doc != "" && pkgDoc[dir] == "" {
				pkgDoc[dir] = doc
			}
		case (strings.HasSuffix(name, ".ts") || strings.HasSuffix(name, ".tsx")) && !strings.HasSuffix(name, ".d.ts"):
			f, err := tsFile(p, rel)
			if err != nil {
				return err
			}
			tsFiles = append(tsFiles, f)
		}
		return nil
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprintln(w, "# Code map")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "<!-- Generated by `make docs-codemap` (hack/codemap). Do not edit by hand. -->")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Every package and file of the repository with its types and functions, and the first sentence of each one's doc comment.")
	fmt.Fprintln(w, "Unexported (lowercase) names are internal to their package. Test files are listed with their test functions.")
	fmt.Fprintln(w, "The [architecture chapters](../architecture/overview.md) explain how these fit together.")
	fmt.Fprintln(w)

	dirs := make([]string, 0, len(pkgs))
	for d := range pkgs {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)
	fmt.Fprintln(w, "## Go packages")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Package | Files | Lines | What it is |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, d := range dirs {
		lines := 0
		for _, f := range pkgs[d] {
			lines += f.lines
		}
		fmt.Fprintf(w, "| [`%s`](#%s) | %d | %d | %s |\n", d, anchor(d), len(pkgs[d]), lines, cell(pkgDoc[d]))
	}
	fmt.Fprintln(w)

	for _, d := range dirs {
		fmt.Fprintf(w, "## `%s` {#%s}\n\n", d, anchor(d))
		if pkgDoc[d] != "" {
			fmt.Fprintf(w, "%s\n\n", pkgDoc[d])
		}
		files := pkgs[d]
		sort.Slice(files, func(i, j int) bool {
			if files[i].test != files[j].test {
				return !files[i].test
			}
			return files[i].path < files[j].path
		})
		for _, f := range files {
			writeFile(w, f)
		}
	}

	sort.Slice(tsFiles, func(i, j int) bool { return tsFiles[i].path < tsFiles[j].path })
	fmt.Fprintln(w, "## Web UI (TypeScript / React) {#web-ui}")
	fmt.Fprintln(w)
	for _, f := range tsFiles {
		writeFile(w, f)
	}
}

func writeFile(w *bufio.Writer, f file) {
	label := ""
	if f.test {
		label = " · tests"
	}
	fmt.Fprintf(w, "### `%s`\n\n<small>%d lines%s</small>", f.path, f.lines, label)
	if f.summary != "" {
		fmt.Fprintf(w, " · %s", f.summary)
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w)
	if len(f.symbols) == 0 {
		return
	}
	fmt.Fprintln(w, "| Name | Kind | Summary |")
	fmt.Fprintln(w, "|---|---|---|")
	for _, s := range f.symbols {
		fmt.Fprintf(w, "| `%s` | %s | %s |\n", s.name, s.kind, cell(s.summary))
	}
	fmt.Fprintln(w)
}

func goFile(path, rel string) (file, string, error) {
	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return file{}, "", err
	}
	data, _ := os.ReadFile(path)
	f := file{path: rel, lines: strings.Count(string(data), "\n"), test: strings.HasSuffix(path, "_test.go")}
	pkgDoc := ""
	if af.Doc != nil {
		pkgDoc = firstSentence(af.Doc.Text())
	}
	for _, decl := range af.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			name := d.Name.Name
			kind := "func"
			if d.Recv != nil && len(d.Recv.List) > 0 {
				kind = "method"
				name = "(" + recvType(d.Recv.List[0].Type) + ") " + name
			}
			if f.test && !strings.HasPrefix(d.Name.Name, "Test") {
				continue // test helpers add noise
			}
			f.symbols = append(f.symbols, symbol{name: name, kind: kind, summary: firstSentence(d.Doc.Text()), exported: d.Name.IsExported()})
		case *ast.GenDecl:
			if d.Tok != token.TYPE || f.test {
				continue
			}
			for _, spec := range d.Specs {
				ts := spec.(*ast.TypeSpec)
				doc := ts.Doc
				if doc == nil {
					doc = d.Doc
				}
				kind := "type"
				switch ts.Type.(type) {
				case *ast.StructType:
					kind = "struct"
				case *ast.InterfaceType:
					kind = "interface"
				}
				f.symbols = append(f.symbols, symbol{name: ts.Name.Name, kind: kind, summary: firstSentence(doc.Text()), exported: ts.Name.IsExported()})
			}
		}
	}
	return f, pkgDoc, nil
}

func recvType(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.StarExpr:
		return "*" + recvType(t.X)
	case *ast.Ident:
		return t.Name
	case *ast.IndexExpr:
		return recvType(t.X)
	}
	return "?"
}

var (
	tsDecl    = regexp.MustCompile(`^(export\s+)?(async\s+)?(function|interface|type|const)\s+([A-Za-z0-9_]+)`)
	tsComment = regexp.MustCompile(`^\s*(/\*\*|//)\s?(.*?)(\*/)?\s*$`)
)

func tsFile(path, rel string) (file, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return file{}, err
	}
	lines := strings.Split(string(data), "\n")
	f := file{path: rel, lines: len(lines) - 1}
	var comment []string
	for _, line := range lines {
		if m := tsDecl.FindStringSubmatch(line); m != nil {
			kind := m[3]
			if kind == "const" && !strings.Contains(line, "=>") && !strings.Contains(line, "= {") {
				comment = nil
				continue // plain constants
			}
			if kind == "function" && len(m[4]) > 0 && m[4][0] >= 'A' && m[4][0] <= 'Z' {
				kind = "component"
			}
			f.symbols = append(f.symbols, symbol{name: m[4], kind: kind, summary: firstSentence(strings.Join(comment, " ")), exported: m[1] != ""})
			comment = nil
			continue
		}
		if c := tsComment.FindStringSubmatch(line); c != nil && !strings.HasPrefix(strings.TrimSpace(line), "//eslint") {
			comment = append(comment, strings.TrimPrefix(strings.TrimSpace(c[2]), "* "))
			continue
		}
		if strings.TrimSpace(line) != "" && !strings.HasPrefix(strings.TrimSpace(line), "*") {
			comment = nil
		}
	}
	return f, nil
}

// firstSentence returns the first sentence of a comment, on one line.
func firstSentence(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	for i := 0; i+1 < len(s); i++ {
		if s[i] == '.' && s[i+1] == ' ' {
			return s[:i+1]
		}
	}
	return s
}

func cell(s string) string { return strings.ReplaceAll(s, "|", "\\|") }

func anchor(s string) string {
	return strings.NewReplacer("/", "-", ".", "-", "_", "-").Replace(strings.ToLower(s))
}
