apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds/rendimiento.ai_apps.yaml
  - crds/rendimiento.ai_addons.yaml
  - rbac.yaml
  - postgres.yaml
  - rendimiento.yaml
  - networkpolicy.yaml
