apiVersion: v1
kind: Namespace
metadata:
  name: rendimiento-system
  labels:
    app.kubernetes.io/managed-by: rendimiento
---
apiVersion: v1
kind: Namespace
metadata:
  name: rendimiento-builds
  labels:
    app.kubernetes.io/managed-by: rendimiento
